export const VALIDATION_REASON = {
  REQUIRED: "REQUIRED",
  INVALID_FORMAT: "INVALID_FORMAT",
  TOO_SHORT: "TOO_SHORT",
  TOO_LONG: "TOO_LONG",
  INVALID_TYPE: "INVALID_TYPE",
  NOT_AGREED: "NOT_AGREED",
} as const;
