export const AUTH_EVENTS = {
  AUTH_SIGNUP_REQUESTED: "AUTH_SIGNUP_REQUESTED",
  AUTH_SIGNUP_COMPLETED: "AUTH_SIGNUP_COMPLETED",
  AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  AUTH_RESEND_REQUESTED: "AUTH_RESEND_REQUESTED",
  AUTH_RESEND_COMPLETED: "AUTH_RESEND_COMPLETED",
  AUTH_RESEND_FAILED: "AUTH_RESEND_FAILED",
  AUTH_CALLBACK_REQUESTED: "AUTH_CALLBACK_REQUESTED",
  AUTH_CALLBACK_COMPLETED: "AUTH_CALLBACK_COMPLETED",
  AUTH_CALLBACK_FAILED: "AUTH_CALLBACK_FAILED",
  AUTH_RATE_LIMIT_BLOCKED: "AUTH_RATE_LIMIT_BLOCKED",
  AUTH_INVALID_INPUT: "AUTH_INVALID_INPUT",
} as const;

export type AuthEvent = (typeof AUTH_EVENTS)[keyof typeof AUTH_EVENTS];

export type RequestedEvent =
  | typeof AUTH_EVENTS.AUTH_SIGNUP_REQUESTED
  | typeof AUTH_EVENTS.AUTH_RESEND_REQUESTED
  | typeof AUTH_EVENTS.AUTH_CALLBACK_REQUESTED;

export type CallbackAuthEvent =
  | typeof AUTH_EVENTS.AUTH_CALLBACK_COMPLETED
  | typeof AUTH_EVENTS.AUTH_CALLBACK_FAILED;

export type BaseAuthEvent = Exclude<
  AuthEvent,
  RequestedEvent | CallbackAuthEvent
>;
