export const AUTH_EVENTS = {
  AUTH_SIGNUP_REQUESTED: "AUTH_SIGNUP_REQUESTED",
  AUTH_SIGNUP_COMPLETED: "AUTH_SIGNUP_COMPLETED",
  AUTH_SIGNUP_FAILED: "AUTH_SIGNUP_FAILED",
  AUTH_RESEND_REQUESTED: "AUTH_RESEND_REQUESTED",
  AUTH_RESEND_COMPLETED: "AUTH_RESEND_COMPLETED",
  AUTH_RESEND_FAILED: "AUTH_RESEND_FAILED",
  AUTH_CALLBACK_REQUESTED: "AUTH_CALLBACK_REQUESTED",
  AUTH_CALLBACK_COMPLETED: "AUTH_CALLBACK_COMPLETED",
  AUTH_CALLBACK_REJECTED: "AUTH_CALLBACK_REJECTED",
} as const;

export type AuthEvent = (typeof AUTH_EVENTS)[keyof typeof AUTH_EVENTS];

export type RequestedAuthEvent =
  | typeof AUTH_EVENTS.AUTH_SIGNUP_REQUESTED
  | typeof AUTH_EVENTS.AUTH_RESEND_REQUESTED
  | typeof AUTH_EVENTS.AUTH_CALLBACK_REQUESTED;

// 주의:
// AUTH_CALLBACK_REJECTED는 예외가 아니라 callback 흐름의 정상적인 분기 결과다.
export type CallbackAuthEvent =
  | typeof AUTH_EVENTS.AUTH_CALLBACK_COMPLETED
  | typeof AUTH_EVENTS.AUTH_CALLBACK_REJECTED;

export type AuthFailureEvent =
  | typeof AUTH_EVENTS.AUTH_SIGNUP_FAILED
  | typeof AUTH_EVENTS.AUTH_RESEND_FAILED;

export type AuthFlowEvent = Exclude<
  AuthEvent,
  RequestedAuthEvent | CallbackAuthEvent
>;

export type AuthNonFailureEvent = Exclude<AuthFlowEvent, AuthFailureEvent>;
