export const AUTH_LOG_REASONS = {
  INVALID_JSON: "INVALID_JSON",
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  RATE_LIMIT_IP: "RATE_LIMIT_IP",
  RATE_LIMIT_EMAIL_SHORT: "RATE_LIMIT_EMAIL_SHORT",
  RATE_LIMIT_EMAIL_LONG: "RATE_LIMIT_EMAIL_LONG",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type AuthLogReason =
  (typeof AUTH_LOG_REASONS)[keyof typeof AUTH_LOG_REASONS];
