/**
 * 관리자 AI 운영 오류 feature입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_FEATURE = "admin-ai";

/**
 * 관리자 AI 운영 오류 코드입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_CODE = {
  AGENT_CREATE_FAILED: "ADMIN_AI_AGENT_CREATE_FAILED",
  AGENT_DELETE_FAILED: "ADMIN_AI_AGENT_DELETE_FAILED",
  AGENT_LOAD_FAILED: "ADMIN_AI_AGENT_LOAD_FAILED",
  AGENT_UPDATE_FAILED: "ADMIN_AI_AGENT_UPDATE_FAILED",
  LIST_RESPONSE_INVALID: "ADMIN_AI_LIST_RESPONSE_INVALID",
  MODEL_CONFIG_CREATE_FAILED: "ADMIN_AI_MODEL_CONFIG_CREATE_FAILED",
  MODEL_CONFIG_DELETE_FAILED: "ADMIN_AI_MODEL_CONFIG_DELETE_FAILED",
  MODEL_CONFIG_LOAD_FAILED: "ADMIN_AI_MODEL_CONFIG_LOAD_FAILED",
  MODEL_CONFIG_UPDATE_FAILED: "ADMIN_AI_MODEL_CONFIG_UPDATE_FAILED",
  PROMPT_FAMILY_CREATE_FAILED: "ADMIN_AI_PROMPT_FAMILY_CREATE_FAILED",
  PROMPT_FAMILY_DELETE_FAILED: "ADMIN_AI_PROMPT_FAMILY_DELETE_FAILED",
  PROMPT_FAMILY_LOAD_FAILED: "ADMIN_AI_PROMPT_FAMILY_LOAD_FAILED",
  PROMPT_FAMILY_UPDATE_FAILED: "ADMIN_AI_PROMPT_FAMILY_UPDATE_FAILED",
  PROMPT_GRAPH_INVALID: "ADMIN_AI_PROMPT_GRAPH_INVALID",
  PROMPT_LOAD_FAILED: "ADMIN_AI_PROMPT_LOAD_FAILED",
  PROMPT_VERSION_ARCHIVE_FAILED: "ADMIN_AI_PROMPT_VERSION_ARCHIVE_FAILED",
  PROMPT_VERSION_CREATE_FAILED: "ADMIN_AI_PROMPT_VERSION_CREATE_FAILED",
  PROMPT_VERSION_DELETE_FAILED: "ADMIN_AI_PROMPT_VERSION_DELETE_FAILED",
  PROMPT_VERSION_LOAD_FAILED: "ADMIN_AI_PROMPT_VERSION_LOAD_FAILED",
  PROMPT_VERSION_PUBLISH_FAILED: "ADMIN_AI_PROMPT_VERSION_PUBLISH_FAILED",
  PROMPT_VERSION_UPDATE_FAILED: "ADMIN_AI_PROMPT_VERSION_UPDATE_FAILED",
  SETTING_CONFIGURATION_INVALID: "ADMIN_AI_SETTING_CONFIGURATION_INVALID",
  SETTING_CONFIG_SAVE_FAILED: "ADMIN_AI_SETTING_CONFIG_SAVE_FAILED",
  SETTING_CREATE_FAILED: "ADMIN_AI_SETTING_CREATE_FAILED",
  SETTING_DELETE_FAILED: "ADMIN_AI_SETTING_DELETE_FAILED",
  SETTING_LOAD_FAILED: "ADMIN_AI_SETTING_LOAD_FAILED",
  SETTING_UPDATE_FAILED: "ADMIN_AI_SETTING_UPDATE_FAILED",
} as const;

/**
 * 관리자 AI 운영 오류 작업입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_OPERATION = {
  CREATE_PROMPT_AGENT: "create_prompt_agent",
  CREATE_PROMPT_FAMILY: "create_prompt_family",
  CREATE_PROMPT_VERSION: "create_prompt_version",
  CREATE_MODEL_CONFIG: "create_model_config",
  CREATE_SETTING: "create_ai_setting",
  DELETE_PROMPT_AGENT: "delete_prompt_agent",
  DELETE_PROMPT_FAMILY: "delete_prompt_family",
  DELETE_PROMPT_VERSION: "delete_prompt_version",
  DELETE_MODEL_CONFIG: "delete_model_config",
  DELETE_SETTING: "delete_ai_setting",
  GET_MODEL_CONFIG: "get_model_config",
  GET_MODEL_CONFIG_OPTIONS: "get_model_config_options",
  GET_PROMPT_AGENT: "get_prompt_agent",
  GET_PROMPT_AGENT_OPTIONS: "get_prompt_agent_options",
  GET_PROMPT_FAMILY: "get_prompt_family",
  GET_PROMPT_FAMILY_OPTIONS: "get_prompt_family_options",
  GET_PROMPT_VERSION: "get_prompt_version",
  GET_PROMPT_VERSION_OPTIONS: "get_prompt_version_options",
  GET_SETTING: "get_ai_setting",
  GET_SETTING_CONFIGURATIONS: "get_ai_setting_configurations",
  GET_SETTINGS: "get_ai_settings",
  PUBLISH_PROMPT_VERSION: "publish_prompt_version",
  ARCHIVE_PROMPT_VERSION: "archive_prompt_version",
  SAVE_SETTING_CONFIGURATIONS: "save_ai_setting_configurations",
  UPDATE_PROMPT_AGENT: "update_prompt_agent",
  UPDATE_PROMPT_FAMILY: "update_prompt_family",
  UPDATE_PROMPT_VERSION: "update_prompt_version",
  UPDATE_MODEL_CONFIG: "update_model_config",
  UPDATE_SETTING: "update_ai_setting",
  VALIDATE_LIST_RESPONSE: "validate_list_response",
  VALIDATE_PROMPT_GRAPH: "validate_prompt_graph",
  VALIDATE_SETTING_CONFIGURATION: "validate_setting_configuration",
} as const;

/**
 * 관리자 AI 운영 오류 단계입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_STAGE = {
  DATABASE: "database",
  VALIDATION: "validation",
} as const;

/**
 * 관리자 AI 운영 오류 코드 타입입니다.
 */
export type AdminAiOperationalErrorCode =
  (typeof ADMIN_AI_OPERATIONAL_ERROR_CODE)[keyof typeof ADMIN_AI_OPERATIONAL_ERROR_CODE];

/**
 * 관리자 AI 운영 오류 작업 타입입니다.
 */
export type AdminAiOperationalErrorOperation =
  (typeof ADMIN_AI_OPERATIONAL_ERROR_OPERATION)[keyof typeof ADMIN_AI_OPERATIONAL_ERROR_OPERATION];

/**
 * 관리자 AI 운영 오류 단계 타입입니다.
 */
export type AdminAiOperationalErrorStage =
  (typeof ADMIN_AI_OPERATIONAL_ERROR_STAGE)[keyof typeof ADMIN_AI_OPERATIONAL_ERROR_STAGE];

/**
 * 관리자 AI 운영 오류 기능의 표시 이름입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_FEATURE_LABELS = {
  [ADMIN_AI_OPERATIONAL_ERROR_FEATURE]: "관리자 AI",
} as const;

/**
 * 관리자 AI 운영 오류 작업의 표시 이름입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_OPERATION_LABELS = {
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.CREATE_MODEL_CONFIG]: "AI 모델 생성",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.CREATE_PROMPT_AGENT]: "AI Agent 생성",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.CREATE_PROMPT_FAMILY]:
    "Prompt Family 생성",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.CREATE_PROMPT_VERSION]:
    "Prompt Version 생성",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.CREATE_SETTING]: "AI 설정 생성",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.DELETE_MODEL_CONFIG]: "AI 모델 삭제",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.DELETE_PROMPT_AGENT]: "AI Agent 삭제",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.DELETE_PROMPT_FAMILY]:
    "Prompt Family 삭제",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.DELETE_PROMPT_VERSION]:
    "Prompt Version 삭제",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.DELETE_SETTING]: "AI 설정 삭제",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_MODEL_CONFIG]: "AI 모델 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_MODEL_CONFIG_OPTIONS]:
    "AI 모델 선택 목록 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_AGENT]: "AI Agent 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_AGENT_OPTIONS]:
    "AI Agent 선택 목록 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_FAMILY]:
    "Prompt Family 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_FAMILY_OPTIONS]:
    "Prompt Family 선택 목록 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_VERSION]:
    "Prompt Version 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_VERSION_OPTIONS]:
    "Prompt Version 선택 목록 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_SETTING]: "AI 설정 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_SETTING_CONFIGURATIONS]:
    "AI 구성 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.GET_SETTINGS]: "AI 설정 목록 조회",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.PUBLISH_PROMPT_VERSION]:
    "Prompt Version 게시",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.ARCHIVE_PROMPT_VERSION]:
    "Prompt Version 보관",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.SAVE_SETTING_CONFIGURATIONS]:
    "AI 구성 저장",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.UPDATE_MODEL_CONFIG]: "AI 모델 수정",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.UPDATE_PROMPT_AGENT]: "AI Agent 수정",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.UPDATE_PROMPT_FAMILY]:
    "Prompt Family 수정",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.UPDATE_PROMPT_VERSION]:
    "Prompt Version 수정",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.UPDATE_SETTING]: "AI 설정 수정",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.VALIDATE_LIST_RESPONSE]:
    "AI 목록 응답 검증",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.VALIDATE_PROMPT_GRAPH]:
    "Prompt Graph 검증",
  [ADMIN_AI_OPERATIONAL_ERROR_OPERATION.VALIDATE_SETTING_CONFIGURATION]:
    "AI 설정 구성 검증",
} as const;

/**
 * 관리자 AI 운영 오류 단계의 표시 이름입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_STAGE_LABELS = {
  [ADMIN_AI_OPERATIONAL_ERROR_STAGE.DATABASE]: "데이터베이스",
  [ADMIN_AI_OPERATIONAL_ERROR_STAGE.VALIDATION]: "검증",
} as const;

/**
 * 관리자 AI 운영 오류 코드의 표시 이름입니다.
 */
export const ADMIN_AI_OPERATIONAL_ERROR_CODE_LABELS = {
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.AGENT_CREATE_FAILED]: "AI Agent 생성 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.AGENT_DELETE_FAILED]: "AI Agent 삭제 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.AGENT_LOAD_FAILED]: "AI Agent 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.AGENT_UPDATE_FAILED]: "AI Agent 수정 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.LIST_RESPONSE_INVALID]:
    "AI 목록 응답 검증 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.MODEL_CONFIG_CREATE_FAILED]:
    "AI 모델 생성 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.MODEL_CONFIG_DELETE_FAILED]:
    "AI 모델 삭제 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.MODEL_CONFIG_LOAD_FAILED]:
    "AI 모델 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.MODEL_CONFIG_UPDATE_FAILED]:
    "AI 모델 수정 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_FAMILY_CREATE_FAILED]:
    "Prompt Family 생성 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_FAMILY_DELETE_FAILED]:
    "Prompt Family 삭제 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_FAMILY_LOAD_FAILED]:
    "Prompt Family 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_FAMILY_UPDATE_FAILED]:
    "Prompt Family 수정 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_GRAPH_INVALID]:
    "Prompt Graph 검증 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_LOAD_FAILED]: "Prompt 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_ARCHIVE_FAILED]:
    "Prompt Version 보관 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_CREATE_FAILED]:
    "Prompt Version 생성 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_DELETE_FAILED]:
    "Prompt Version 삭제 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_LOAD_FAILED]:
    "Prompt Version 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_PUBLISH_FAILED]:
    "Prompt Version 게시 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_UPDATE_FAILED]:
    "Prompt Version 수정 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_CONFIGURATION_INVALID]:
    "AI 설정 구성 검증 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_CONFIG_SAVE_FAILED]:
    "AI 구성 저장 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_CREATE_FAILED]: "AI 설정 생성 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_DELETE_FAILED]: "AI 설정 삭제 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_LOAD_FAILED]: "AI 설정 조회 실패",
  [ADMIN_AI_OPERATIONAL_ERROR_CODE.SETTING_UPDATE_FAILED]: "AI 설정 수정 실패",
} as const;
