/**
 * AI Foundation 공통 운영 오류 feature입니다.
 */
export const AI_OPERATIONAL_ERROR_FEATURE = "ai";

/**
 * AI Foundation 운영 오류 기능의 표시 이름입니다.
 */
export const AI_OPERATIONAL_ERROR_FEATURE_LABELS = {
  [AI_OPERATIONAL_ERROR_FEATURE]: "AI",
} as const;

/**
 * AI Foundation 공통 운영 오류 코드입니다.
 */
export const AI_OPERATIONAL_ERROR_CODE = {
  EMBEDDING_ACTIVATION_FAILED: "AI_EMBEDDING_ACTIVATION_FAILED",
  EMBEDDING_CACHE_READ_FAILED: "AI_EMBEDDING_CACHE_READ_FAILED",
  EMBEDDING_DELETE_FAILED: "AI_EMBEDDING_DELETE_FAILED",
  EMBEDDING_DIMENSIONS_MISSING: "AI_EMBEDDING_DIMENSIONS_MISSING",
  EMBEDDING_DIMENSIONS_UNSUPPORTED: "AI_EMBEDDING_DIMENSIONS_UNSUPPORTED",
  EMBEDDING_INSERT_FAILED: "AI_EMBEDDING_INSERT_FAILED",
  EMBEDDING_SOURCE_LOAD_FAILED: "AI_EMBEDDING_SOURCE_LOAD_FAILED",
  GOOGLE_CHAT_FAILED: "AI_GOOGLE_CHAT_FAILED",
  GOOGLE_EMBEDDING_FAILED: "AI_GOOGLE_EMBEDDING_FAILED",
  MODEL_CONFIG_LOAD_FAILED: "AI_MODEL_CONFIG_LOAD_FAILED",
  OPENAI_CHAT_FAILED: "AI_OPENAI_CHAT_FAILED",
  OPENAI_EMBEDDING_FAILED: "AI_OPENAI_EMBEDDING_FAILED",
  PROMPT_AGENT_LOAD_FAILED: "AI_PROMPT_AGENT_LOAD_FAILED",
  PROMPT_FAMILY_LOAD_FAILED: "AI_PROMPT_FAMILY_LOAD_FAILED",
  PROMPT_VERSION_LOAD_FAILED: "AI_PROMPT_VERSION_LOAD_FAILED",
  PROVIDER_API_KEY_MISSING: "AI_PROVIDER_API_KEY_MISSING",
  RUNTIME_CONFIGURATION_LOAD_FAILED: "AI_RUNTIME_CONFIGURATION_LOAD_FAILED",
  VECTOR_MATCH_FAILED: "AI_VECTOR_MATCH_FAILED",
} as const;

/**
 * AI Foundation 운영 오류 코드의 표시 이름입니다.
 */
export const AI_OPERATIONAL_ERROR_CODE_LABELS = {
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_ACTIVATION_FAILED]:
    "Embedding Generation 활성화 실패",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_CACHE_READ_FAILED]:
    "Embedding Cache 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_DELETE_FAILED]: "Embedding 삭제 실패",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_DIMENSIONS_MISSING]:
    "Embedding dimensions 설정 누락",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_DIMENSIONS_UNSUPPORTED]:
    "지원하지 않는 Embedding dimensions",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_INSERT_FAILED]: "Embedding 저장 실패",
  [AI_OPERATIONAL_ERROR_CODE.EMBEDDING_SOURCE_LOAD_FAILED]:
    "Embedding Source 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.GOOGLE_CHAT_FAILED]: "Google Chat 실패",
  [AI_OPERATIONAL_ERROR_CODE.GOOGLE_EMBEDDING_FAILED]: "Google Embedding 실패",
  [AI_OPERATIONAL_ERROR_CODE.MODEL_CONFIG_LOAD_FAILED]:
    "Model Config 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.OPENAI_CHAT_FAILED]: "OpenAI Chat 실패",
  [AI_OPERATIONAL_ERROR_CODE.OPENAI_EMBEDDING_FAILED]: "OpenAI Embedding 실패",
  [AI_OPERATIONAL_ERROR_CODE.PROMPT_AGENT_LOAD_FAILED]:
    "Prompt Agent 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.PROMPT_FAMILY_LOAD_FAILED]:
    "Prompt Family 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.PROMPT_VERSION_LOAD_FAILED]:
    "Prompt Version 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.PROVIDER_API_KEY_MISSING]:
    "Provider API Key 설정 누락",
  [AI_OPERATIONAL_ERROR_CODE.RUNTIME_CONFIGURATION_LOAD_FAILED]:
    "Runtime Configuration 조회 실패",
  [AI_OPERATIONAL_ERROR_CODE.VECTOR_MATCH_FAILED]: "Vector 매칭 실패",
} as const;

/**
 * AI Foundation 공통 운영 오류 작업입니다.
 */
export const AI_OPERATIONAL_ERROR_OPERATION = {
  ACTIVATE_EMBEDDING_GENERATION: "activate_embedding_generation",
  CREATE_CHAT_COMPLETION: "create_chat_completion",
  CREATE_EMBEDDING: "create_embedding",
  DELETE_EMBEDDING: "delete_embedding",
  GET_EMBEDDING_CACHE: "get_embedding_cache",
  GET_EMBEDDING_SOURCE: "get_embedding_source",
  GET_MODEL_CONFIG: "get_model_config",
  GET_PROMPT_AGENT: "get_prompt_agent",
  GET_PROMPT_FAMILY: "get_prompt_family",
  GET_PROMPT_VERSION: "get_prompt_version",
  GET_RUNTIME_CONFIGURATION: "get_runtime_configuration",
  INSERT_EMBEDDING: "insert_embedding",
  MATCH_EMBEDDINGS: "match_embeddings",
} as const;

/**
 * AI Foundation 운영 오류 작업의 표시 이름입니다.
 */
export const AI_OPERATIONAL_ERROR_OPERATION_LABELS = {
  [AI_OPERATIONAL_ERROR_OPERATION.ACTIVATE_EMBEDDING_GENERATION]:
    "Embedding Generation 활성화",
  [AI_OPERATIONAL_ERROR_OPERATION.CREATE_CHAT_COMPLETION]:
    "Chat Completion 생성",
  [AI_OPERATIONAL_ERROR_OPERATION.CREATE_EMBEDDING]: "Embedding 생성",
  [AI_OPERATIONAL_ERROR_OPERATION.DELETE_EMBEDDING]: "Embedding 삭제",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_EMBEDDING_CACHE]: "Embedding Cache 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_EMBEDDING_SOURCE]:
    "Embedding Source 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_MODEL_CONFIG]: "Model Config 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_AGENT]: "Prompt Agent 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_FAMILY]: "Prompt Family 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_PROMPT_VERSION]: "Prompt Version 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.GET_RUNTIME_CONFIGURATION]:
    "Runtime Configuration 조회",
  [AI_OPERATIONAL_ERROR_OPERATION.INSERT_EMBEDDING]: "Embedding 저장",
  [AI_OPERATIONAL_ERROR_OPERATION.MATCH_EMBEDDINGS]: "Embedding 매칭",
} as const;

/**
 * AI Foundation 공통 운영 오류 단계입니다.
 */
export const AI_OPERATIONAL_ERROR_STAGE = {
  DATABASE: "database",
  PROVIDER: "provider",
  VALIDATION: "validation",
} as const;

/**
 * AI Foundation 운영 오류 단계의 표시 이름입니다.
 */
export const AI_OPERATIONAL_ERROR_STAGE_LABELS = {
  [AI_OPERATIONAL_ERROR_STAGE.DATABASE]: "데이터베이스",
  [AI_OPERATIONAL_ERROR_STAGE.PROVIDER]: "Provider",
  [AI_OPERATIONAL_ERROR_STAGE.VALIDATION]: "검증",
} as const;

/**
 * AI Foundation 운영 오류 코드 타입입니다.
 */
export type AiOperationalErrorCode =
  (typeof AI_OPERATIONAL_ERROR_CODE)[keyof typeof AI_OPERATIONAL_ERROR_CODE];

/**
 * AI Foundation 운영 오류 작업 타입입니다.
 */
export type AiOperationalErrorOperation =
  (typeof AI_OPERATIONAL_ERROR_OPERATION)[keyof typeof AI_OPERATIONAL_ERROR_OPERATION];

/**
 * AI Foundation 운영 오류 단계 타입입니다.
 */
export type AiOperationalErrorStage =
  (typeof AI_OPERATIONAL_ERROR_STAGE)[keyof typeof AI_OPERATIONAL_ERROR_STAGE];
