import {
  ADMIN_AI_OPERATIONAL_ERROR_CODE,
  ADMIN_AI_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_FEATURE,
  ADMIN_AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_OPERATION,
  ADMIN_AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_STAGE,
  ADMIN_AI_OPERATIONAL_ERROR_STAGE_LABELS,
} from "./admin-ai";
import {
  ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_OPERATIONAL_ERROR_CODES,
  ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_OPERATIONAL_ERROR_FEATURES,
  ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_OPERATIONAL_ERROR_STAGES,
} from "./admin-operational-errors";
import {
  ADMIN_USER_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_CODES,
  ADMIN_USER_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_FEATURES,
  ADMIN_USER_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_USER_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_STAGES,
} from "./admin-users";
import {
  AI_OPERATIONAL_ERROR_CODE,
  AI_OPERATIONAL_ERROR_CODE_LABELS,
  AI_OPERATIONAL_ERROR_FEATURE,
  AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  AI_OPERATIONAL_ERROR_OPERATION,
  AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  AI_OPERATIONAL_ERROR_STAGE,
  AI_OPERATIONAL_ERROR_STAGE_LABELS,
} from "./ai";
import {
  OPERATIONAL_ERROR_SEVERITY,
  OPERATIONAL_ERROR_SEVERITY_LABELS,
  OPERATIONAL_ERROR_STATUS,
  OPERATIONAL_ERROR_STATUS_LABELS,
} from "./common";
import {
  NOTE_CHAT_OPERATIONAL_ERROR_CODE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_CODES,
  NOTE_CHAT_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_FEATURES,
  NOTE_CHAT_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS,
  NOTE_CHAT_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_STAGES,
} from "./note-chat";
import {
  NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_CODES,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGES,
} from "./notifications";
import {
  RELATED_NOTES_OPERATIONAL_ERROR_CODE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_CODES,
  RELATED_NOTES_OPERATIONAL_ERROR_FEATURE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_FEATURES,
  RELATED_NOTES_OPERATIONAL_ERROR_OPERATION_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS,
  RELATED_NOTES_OPERATIONAL_ERROR_STAGE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_STAGES,
} from "./related-notes";

/**
 * 운영 오류가 발생한 기능 도메인입니다.
 */
export const OPERATIONAL_ERROR_FEATURES = {
  AI: AI_OPERATIONAL_ERROR_FEATURE,
  ADMIN_AI: ADMIN_AI_OPERATIONAL_ERROR_FEATURE,
  ...NOTE_CHAT_OPERATIONAL_ERROR_FEATURES,
  ...RELATED_NOTES_OPERATIONAL_ERROR_FEATURES,
  ...NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  ...ADMIN_OPERATIONAL_ERROR_FEATURES,
  ...ADMIN_USER_OPERATIONAL_ERROR_FEATURES,
} as const;

/**
 * 운영 오류 기능의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_FEATURE_LABELS = {
  ...AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...ADMIN_AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...NOTE_CHAT_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...RELATED_NOTES_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...ADMIN_USER_OPERATIONAL_ERROR_FEATURE_LABELS,
} as const;

/**
 * 운영 오류가 발생한 작업입니다.
 */
export const OPERATIONAL_ERROR_OPERATIONS = {
  ...AI_OPERATIONAL_ERROR_OPERATION,
  ...ADMIN_AI_OPERATIONAL_ERROR_OPERATION,
  ...NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS,
  ...RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS,
  ...NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  ...ADMIN_OPERATIONAL_ERROR_OPERATIONS,
  ...ADMIN_USER_OPERATIONAL_ERROR_OPERATIONS,
} as const;

/**
 * 운영 오류 작업의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_OPERATION_LABELS = {
  ...AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...ADMIN_AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...NOTE_CHAT_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...RELATED_NOTES_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...ADMIN_USER_OPERATIONAL_ERROR_OPERATION_LABELS,
} as const;

/**
 * 운영 오류가 발생한 작업 내부의 세부 단계입니다.
 */
export const OPERATIONAL_ERROR_STAGES = {
  ...AI_OPERATIONAL_ERROR_STAGE,
  ...ADMIN_AI_OPERATIONAL_ERROR_STAGE,
  ...NOTE_CHAT_OPERATIONAL_ERROR_STAGES,
  ...RELATED_NOTES_OPERATIONAL_ERROR_STAGES,
  ...NOTIFICATION_OPERATIONAL_ERROR_STAGES,
  ...ADMIN_OPERATIONAL_ERROR_STAGES,
  ...ADMIN_USER_OPERATIONAL_ERROR_STAGES,
} as const;

/**
 * 운영 오류 단계의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_STAGE_LABELS = {
  ...AI_OPERATIONAL_ERROR_STAGE_LABELS,
  ...ADMIN_AI_OPERATIONAL_ERROR_STAGE_LABELS,
  ...NOTE_CHAT_OPERATIONAL_ERROR_STAGE_LABELS,
  ...RELATED_NOTES_OPERATIONAL_ERROR_STAGE_LABELS,
  ...NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
  ...ADMIN_USER_OPERATIONAL_ERROR_STAGE_LABELS,
} as const;

/**
 * 운영 오류를 식별하기 위한 고유 코드입니다.
 */
export const OPERATIONAL_ERROR_CODES = {
  ...AI_OPERATIONAL_ERROR_CODE,
  ...ADMIN_AI_OPERATIONAL_ERROR_CODE,
  ...NOTE_CHAT_OPERATIONAL_ERROR_CODES,
  ...RELATED_NOTES_OPERATIONAL_ERROR_CODES,
  ...NOTIFICATION_OPERATIONAL_ERROR_CODES,
  ...ADMIN_OPERATIONAL_ERROR_CODES,
  ...ADMIN_USER_OPERATIONAL_ERROR_CODES,
} as const;

/**
 * 운영 오류 코드의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_CODE_LABELS = {
  ...AI_OPERATIONAL_ERROR_CODE_LABELS,
  ...ADMIN_AI_OPERATIONAL_ERROR_CODE_LABELS,
  ...NOTE_CHAT_OPERATIONAL_ERROR_CODE_LABELS,
  ...RELATED_NOTES_OPERATIONAL_ERROR_CODE_LABELS,
  ...NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
  ...ADMIN_USER_OPERATIONAL_ERROR_CODE_LABELS,
} as const;

export type {
  AdminAiOperationalErrorCode,
  AdminAiOperationalErrorOperation,
  AdminAiOperationalErrorStage,
} from "./admin-ai";
export type {
  AiOperationalErrorCode,
  AiOperationalErrorOperation,
  AiOperationalErrorStage,
} from "./ai";
export type {
  OperationalErrorSeverityType,
  OperationalErrorStatusType,
} from "./common";
export type {
  NoteChatOperationalErrorCodeType,
  NoteChatOperationalErrorOperationType,
  NoteChatOperationalErrorStageType,
} from "./note-chat";
export type { NotificationOperationalErrorOperationType } from "./notifications";
export type {
  RelatedNotesOperationalErrorCodeType,
  RelatedNotesOperationalErrorOperationType,
  RelatedNotesOperationalErrorStageType,
} from "./related-notes";

export {
  OPERATIONAL_ERROR_SEVERITY,
  OPERATIONAL_ERROR_SEVERITY_LABELS,
  OPERATIONAL_ERROR_STATUS,
  OPERATIONAL_ERROR_STATUS_LABELS,
};

export {
  ADMIN_AI_OPERATIONAL_ERROR_CODE,
  ADMIN_AI_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_FEATURE,
  ADMIN_AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_OPERATION,
  ADMIN_AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_AI_OPERATIONAL_ERROR_STAGE,
  ADMIN_AI_OPERATIONAL_ERROR_STAGE_LABELS,
} from "./admin-ai";
export {
  ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_OPERATIONAL_ERROR_CODES,
  ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_OPERATIONAL_ERROR_FEATURES,
  ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_OPERATIONAL_ERROR_STAGES,
} from "./admin-operational-errors";
export {
  ADMIN_USER_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_CODES,
  ADMIN_USER_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_FEATURES,
  ADMIN_USER_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_USER_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_USER_OPERATIONAL_ERROR_STAGES,
} from "./admin-users";
export {
  AI_OPERATIONAL_ERROR_CODE,
  AI_OPERATIONAL_ERROR_CODE_LABELS,
  AI_OPERATIONAL_ERROR_FEATURE,
  AI_OPERATIONAL_ERROR_FEATURE_LABELS,
  AI_OPERATIONAL_ERROR_OPERATION,
  AI_OPERATIONAL_ERROR_OPERATION_LABELS,
  AI_OPERATIONAL_ERROR_STAGE,
  AI_OPERATIONAL_ERROR_STAGE_LABELS,
} from "./ai";
export {
  NOTE_CHAT_OPERATIONAL_ERROR_CODE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_CODES,
  NOTE_CHAT_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_FEATURES,
  NOTE_CHAT_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS,
  NOTE_CHAT_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTE_CHAT_OPERATIONAL_ERROR_STAGES,
} from "./note-chat";
export {
  NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_CODES,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGES,
} from "./notifications";
export {
  RELATED_NOTES_OPERATIONAL_ERROR_CODE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_CODES,
  RELATED_NOTES_OPERATIONAL_ERROR_FEATURE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_FEATURES,
  RELATED_NOTES_OPERATIONAL_ERROR_OPERATION_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS,
  RELATED_NOTES_OPERATIONAL_ERROR_STAGE_LABELS,
  RELATED_NOTES_OPERATIONAL_ERROR_STAGES,
} from "./related-notes";
