import {
  ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_OPERATIONAL_ERROR_CODES,
  ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_OPERATIONAL_ERROR_FEATURES,
  ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_OPERATIONAL_ERROR_STAGES,
} from "./admin-operational-errors";
import {
  OPERATIONAL_ERROR_SEVERITY,
  OPERATIONAL_ERROR_SEVERITY_LABELS,
  OPERATIONAL_ERROR_STATUS,
  OPERATIONAL_ERROR_STATUS_LABELS,
} from "./common";
import {
  NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_CODES,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGES,
} from "./notifications";

/**
 * 운영 오류가 발생한 기능 도메인입니다.
 */
export const OPERATIONAL_ERROR_FEATURES = {
  ...NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  ...ADMIN_OPERATIONAL_ERROR_FEATURES,
} as const;

/**
 * 운영 오류 기능의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_FEATURE_LABELS = {
  ...NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
} as const;

/**
 * 운영 오류가 발생한 작업입니다.
 */
export const OPERATIONAL_ERROR_OPERATIONS = {
  ...NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  ...ADMIN_OPERATIONAL_ERROR_OPERATIONS,
} as const;

/**
 * 운영 오류 작업의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_OPERATION_LABELS = {
  ...NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
} as const;

/**
 * 운영 오류가 발생한 작업 내부의 세부 단계입니다.
 */
export const OPERATIONAL_ERROR_STAGES = {
  ...NOTIFICATION_OPERATIONAL_ERROR_STAGES,
  ...ADMIN_OPERATIONAL_ERROR_STAGES,
} as const;

/**
 * 운영 오류 단계의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_STAGE_LABELS = {
  ...NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
} as const;

/**
 * 운영 오류를 식별하기 위한 고유 코드입니다.
 */
export const OPERATIONAL_ERROR_CODES = {
  ...NOTIFICATION_OPERATIONAL_ERROR_CODES,
  ...ADMIN_OPERATIONAL_ERROR_CODES,
} as const;

/**
 * 운영 오류 코드의 표시 이름입니다.
 */
export const OPERATIONAL_ERROR_CODE_LABELS = {
  ...NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  ...ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
} as const;

export type {
  OperationalErrorSeverityType,
  OperationalErrorStatusType,
} from "./common";

export {
  OPERATIONAL_ERROR_SEVERITY,
  OPERATIONAL_ERROR_SEVERITY_LABELS,
  OPERATIONAL_ERROR_STATUS,
  OPERATIONAL_ERROR_STATUS_LABELS,
};

export {
  ADMIN_OPERATIONAL_ERROR_CODE_LABELS,
  ADMIN_OPERATIONAL_ERROR_CODES,
  ADMIN_OPERATIONAL_ERROR_FEATURE_LABELS,
  ADMIN_OPERATIONAL_ERROR_FEATURES,
  ADMIN_OPERATIONAL_ERROR_OPERATION_LABELS,
  ADMIN_OPERATIONAL_ERROR_OPERATIONS,
  ADMIN_OPERATIONAL_ERROR_STAGE_LABELS,
  ADMIN_OPERATIONAL_ERROR_STAGES,
} from "./admin-operational-errors";
export {
  NOTIFICATION_OPERATIONAL_ERROR_CODE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_CODES,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_FEATURES,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATION_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_OPERATIONS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGE_LABELS,
  NOTIFICATION_OPERATIONAL_ERROR_STAGES,
} from "./notifications";
