/**
 * 노트 챗봇 운영 오류 기능입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_FEATURES = {
  NOTE_CHAT: "note-chat",
} as const;

/**
 * 노트 챗봇 운영 오류 기능의 표시 이름입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_FEATURE_LABELS = {
  [NOTE_CHAT_OPERATIONAL_ERROR_FEATURES.NOTE_CHAT]: "노트 챗봇",
} as const;

/**
 * 노트 챗봇에서 운영 오류를 기록하는 작업입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS = {
  CREATE_CONVERSATION: "create_conversation",
  DELETE_CONVERSATION: "delete_conversation",
  GET_CONVERSATION: "get_conversation",
  GET_CONVERSATION_LIST: "get_conversation_list",
  GET_MESSAGES: "get_messages",
  GET_SOURCES: "get_sources",
  UPDATE_CONVERSATION_TITLE: "update_conversation_title",

  LOAD_AI_CONFIGURATION: "load_ai_configuration",
  CREATE_QUESTION: "create_question",
  LOAD_USER_MESSAGE: "load_user_message",
  UPDATE_USER_MESSAGE: "update_user_message",

  CLAIM_EXECUTION: "claim_execution",
  COMPLETE_EXECUTION_CLAIM: "complete_execution_claim",
  CREATE_ASSISTANT_MESSAGE: "create_assistant_message",
  CREATE_RUN: "create_run",
  UPDATE_RUN: "update_run",
  SAVE_EXPANDED_QUERY: "save_expanded_query",
  COMPLETE_RUN_SUCCESS: "complete_run_success",
  COMPLETE_RUN_FAILURE: "complete_run_failure",

  GET_MATCHED_NOTES: "get_matched_notes",

  PARSE_PROVIDER_RESPONSE: "parse_provider_response",
  RESOLVE_USED_NOTES: "resolve_used_notes",
  CONSUME_PROVIDER_STREAM: "consume_provider_stream",

  VALIDATE_EXECUTION_STATE: "validate_execution_state",

  PARSE_QUERY_EXPANSION_RESPONSE: "parse_query_expansion_response",

  VALIDATE_EMBEDDING_CONFIGURATION: "validate_embedding_configuration",

  RESOLVE_EXECUTION_MESSAGES: "resolve_execution_messages",
} as const;

/**
 * 노트 챗봇 운영 오류 작업의 표시 이름입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_OPERATION_LABELS = {
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CREATE_CONVERSATION]: "대화 생성",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.DELETE_CONVERSATION]: "대화 삭제",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.GET_CONVERSATION]: "대화 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.GET_CONVERSATION_LIST]:
    "대화 목록 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.GET_MESSAGES]: "메시지 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.GET_SOURCES]: "참고 노트 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.UPDATE_CONVERSATION_TITLE]:
    "대화 제목 변경",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.LOAD_AI_CONFIGURATION]:
    "AI 실행 설정 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CREATE_QUESTION]: "질문 생성",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.LOAD_USER_MESSAGE]:
    "사용자 메시지 조회",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.UPDATE_USER_MESSAGE]:
    "사용자 메시지 수정",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CLAIM_EXECUTION]: "실행 선점",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_EXECUTION_CLAIM]:
    "실행 선점 완료",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CREATE_ASSISTANT_MESSAGE]:
    "Assistant 메시지 생성",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CREATE_RUN]: "Run 생성",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.UPDATE_RUN]: "Run 갱신",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.SAVE_EXPANDED_QUERY]:
    "확장 질의 저장",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_RUN_SUCCESS]:
    "Run 성공 완료 처리",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_RUN_FAILURE]:
    "Run 실패 완료 처리",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.GET_MATCHED_NOTES]: "검색 노트 조회",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.PARSE_PROVIDER_RESPONSE]:
    "Provider 응답 파싱",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_USED_NOTES]: "사용 노트 확인",
  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.CONSUME_PROVIDER_STREAM]:
    "Provider 스트림 처리",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_EXECUTION_STATE]:
    "실행 상태 검증",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.PARSE_QUERY_EXPANSION_RESPONSE]:
    "질의 확장 응답 파싱",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_EMBEDDING_CONFIGURATION]:
    "Embedding 설정 검증",

  [NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_EXECUTION_MESSAGES]:
    "실행 메시지 구성",
} as const;

/**
 * 노트 챗봇 작업 내부의 운영 오류 단계입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_STAGES = {
  DATABASE: "database",

  CONFIGURATION: "configuration",
  EXECUTION_LIMIT: "execution_limit",
  EXECUTION: "execution",
} as const;

/**
 * 노트 챗봇 운영 오류 단계의 표시 이름입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_STAGE_LABELS = {
  [NOTE_CHAT_OPERATIONAL_ERROR_STAGES.DATABASE]: "데이터베이스",

  [NOTE_CHAT_OPERATIONAL_ERROR_STAGES.CONFIGURATION]: "실행 설정",
  [NOTE_CHAT_OPERATIONAL_ERROR_STAGES.EXECUTION_LIMIT]: "실행 제한",
  [NOTE_CHAT_OPERATIONAL_ERROR_STAGES.EXECUTION]: "실행",
} as const;

/**
 * 노트 챗봇 운영 오류를 식별하는 코드입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_CODES = {
  CONVERSATION_CREATE_FAILED: "NOTE_CHAT_CONVERSATION_CREATE_FAILED",
  CONVERSATION_DELETE_FAILED: "NOTE_CHAT_CONVERSATION_DELETE_FAILED",
  CONVERSATION_LIST_LOAD_FAILED: "NOTE_CHAT_CONVERSATION_LIST_LOAD_FAILED",
  CONVERSATION_LOAD_FAILED: "NOTE_CHAT_CONVERSATION_LOAD_FAILED",
  CONVERSATION_TITLE_UPDATE_FAILED:
    "NOTE_CHAT_CONVERSATION_TITLE_UPDATE_FAILED",
  MESSAGES_LOAD_FAILED: "NOTE_CHAT_MESSAGES_LOAD_FAILED",
  SOURCES_LOAD_FAILED: "NOTE_CHAT_SOURCES_LOAD_FAILED",

  AI_CONFIGURATION_LOAD_FAILED: "NOTE_CHAT_AI_CONFIGURATION_LOAD_FAILED",
  QUESTION_CREATE_FAILED: "NOTE_CHAT_QUESTION_CREATE_FAILED",
  USER_MESSAGE_LOAD_FAILED: "NOTE_CHAT_USER_MESSAGE_LOAD_FAILED",
  USER_MESSAGE_UPDATE_FAILED: "NOTE_CHAT_USER_MESSAGE_UPDATE_FAILED",

  EXECUTION_CLAIM_FAILED: "NOTE_CHAT_EXECUTION_CLAIM_FAILED",
  EXECUTION_CLAIM_COMPLETE_FAILED: "NOTE_CHAT_EXECUTION_CLAIM_COMPLETE_FAILED",
  ASSISTANT_MESSAGE_CREATE_FAILED: "NOTE_CHAT_ASSISTANT_MESSAGE_CREATE_FAILED",
  RUN_CREATE_FAILED: "NOTE_CHAT_RUN_CREATE_FAILED",
  RUN_UPDATE_FAILED: "NOTE_CHAT_RUN_UPDATE_FAILED",
  EXPANDED_QUERY_SAVE_FAILED: "NOTE_CHAT_EXPANDED_QUERY_SAVE_FAILED",
  RUN_SUCCESS_COMPLETE_FAILED: "NOTE_CHAT_RUN_SUCCESS_COMPLETE_FAILED",
  RUN_FAILURE_COMPLETE_FAILED: "NOTE_CHAT_RUN_FAILURE_COMPLETE_FAILED",

  MATCHED_NOTES_LOAD_FAILED: "NOTE_CHAT_MATCHED_NOTES_LOAD_FAILED",

  PROVIDER_RESPONSE_PARSE_FAILED: "NOTE_CHAT_PROVIDER_RESPONSE_PARSE_FAILED",
  USED_NOTES_RESOLVE_FAILED: "NOTE_CHAT_USED_NOTES_RESOLVE_FAILED",
  PROVIDER_STREAM_CONSUME_FAILED: "NOTE_CHAT_PROVIDER_STREAM_CONSUME_FAILED",

  EXECUTION_STATE_INVALID: "NOTE_CHAT_EXECUTION_STATE_INVALID",

  QUERY_EXPANSION_RESPONSE_PARSE_FAILED:
    "NOTE_CHAT_QUERY_EXPANSION_RESPONSE_PARSE_FAILED",

  EMBEDDING_CONFIGURATION_INVALID: "NOTE_CHAT_EMBEDDING_CONFIGURATION_INVALID",

  EXECUTION_MESSAGES_RESOLVE_FAILED:
    "NOTE_CHAT_EXECUTION_MESSAGES_RESOLVE_FAILED",
} as const;

/**
 * 노트 챗봇 운영 오류 코드의 표시 이름입니다.
 */
export const NOTE_CHAT_OPERATIONAL_ERROR_CODE_LABELS = {
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.CONVERSATION_CREATE_FAILED]:
    "대화 생성 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.CONVERSATION_DELETE_FAILED]:
    "대화 삭제 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.CONVERSATION_LIST_LOAD_FAILED]:
    "대화 목록 조회 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.CONVERSATION_LOAD_FAILED]:
    "대화 조회 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.CONVERSATION_TITLE_UPDATE_FAILED]:
    "대화 제목 변경 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.MESSAGES_LOAD_FAILED]: "메시지 조회 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.SOURCES_LOAD_FAILED]:
    "참고 노트 조회 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.AI_CONFIGURATION_LOAD_FAILED]:
    "AI 실행 설정 조회 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.QUESTION_CREATE_FAILED]: "질문 생성 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.USER_MESSAGE_LOAD_FAILED]:
    "사용자 메시지 조회 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.USER_MESSAGE_UPDATE_FAILED]:
    "사용자 메시지 수정 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EXECUTION_CLAIM_FAILED]: "실행 선점 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EXECUTION_CLAIM_COMPLETE_FAILED]:
    "실행 선점 완료 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.ASSISTANT_MESSAGE_CREATE_FAILED]:
    "Assistant 메시지 생성 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.RUN_CREATE_FAILED]: "Run 생성 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.RUN_UPDATE_FAILED]: "Run 갱신 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EXPANDED_QUERY_SAVE_FAILED]:
    "확장 질의 저장 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.RUN_SUCCESS_COMPLETE_FAILED]:
    "Run 성공 완료 처리 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.RUN_FAILURE_COMPLETE_FAILED]:
    "Run 실패 완료 처리 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.MATCHED_NOTES_LOAD_FAILED]:
    "검색 노트 조회 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.PROVIDER_RESPONSE_PARSE_FAILED]:
    "Provider 응답 파싱 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.USED_NOTES_RESOLVE_FAILED]:
    "사용 노트 확인 실패",
  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.PROVIDER_STREAM_CONSUME_FAILED]:
    "Provider 스트림 처리 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EXECUTION_STATE_INVALID]:
    "실행 상태 검증 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.QUERY_EXPANSION_RESPONSE_PARSE_FAILED]:
    "질의 확장 응답 파싱 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EMBEDDING_CONFIGURATION_INVALID]:
    "Embedding 설정 검증 실패",

  [NOTE_CHAT_OPERATIONAL_ERROR_CODES.EXECUTION_MESSAGES_RESOLVE_FAILED]:
    "실행 메시지 구성 실패",
} as const;

export type NoteChatOperationalErrorOperationType =
  (typeof NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS)[keyof typeof NOTE_CHAT_OPERATIONAL_ERROR_OPERATIONS];

export type NoteChatOperationalErrorStageType =
  (typeof NOTE_CHAT_OPERATIONAL_ERROR_STAGES)[keyof typeof NOTE_CHAT_OPERATIONAL_ERROR_STAGES];

export type NoteChatOperationalErrorCodeType =
  (typeof NOTE_CHAT_OPERATIONAL_ERROR_CODES)[keyof typeof NOTE_CHAT_OPERATIONAL_ERROR_CODES];
