/**
 * Related Notes 운영 오류 기능입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_FEATURES = {
  RELATED_NOTES: "related-notes",
} as const;

/**
 * Related Notes 운영 오류 기능의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_FEATURE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_FEATURES.RELATED_NOTES]: "Related Notes",
} as const;

/**
 * Related Notes에서 운영 오류를 기록하는 작업입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS = {
  LOAD_SOURCE_NOTE: "load_source_note",
  LOAD_RELATED_NOTES: "load_related_notes",
  LOAD_RECOMMENDATION_EXECUTION_STATE: "load_recommendation_execution_state",
  LOAD_RELATED_NOTE_CANDIDATES: "load_related_note_candidates",

  LOAD_RECOMMENDATION_SOURCE: "load_recommendation_source",

  LOAD_RECOMMENDATION_EXCLUSIONS: "load_recommendation_exclusions",

  PARSE_QUERY_EXPANSION_RESPONSE: "parse_query_expansion_response",
  VALIDATE_QUERY_EXPANSION_RESPONSE: "validate_query_expansion_response",

  PARSE_RECOMMENDATION_RESPONSE: "parse_recommendation_response",
  VALIDATE_RECOMMENDATION_RESPONSE: "validate_recommendation_response",
  RESOLVE_RECOMMENDATIONS: "resolve_recommendations",

  PARSE_VERIFICATION_RESPONSE: "parse_verification_response",
  VALIDATE_VERIFICATION_RESPONSE: "validate_verification_response",
  RESOLVE_VERIFICATIONS: "resolve_verifications",

  REPLACE_RECOMMENDATIONS: "replace_recommendations",

  CLAIM_RECOMMENDATION_EXECUTION: "claim_recommendation_execution",
  COMPLETE_RECOMMENDATION_EXECUTION_CLAIM:
    "complete_recommendation_execution_claim",

  /*
   * Related Notes 화면에서 현재 Note의 일일 AI 추천 사용량을 조회하는 작업입니다.
   *
   * 실제 quota 판정은 execution claim RPC가 담당하며,
   * 이 operation은 사용자에게 현재 사용량을 표시하기 위한 조회 실패를 기록합니다.
   */
  GET_DAILY_USAGE: "get_daily_usage",
} as const;

/**
 * Related Notes 운영 오류 작업의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_OPERATION_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_SOURCE_NOTE]:
    "기준 Note 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RELATED_NOTES]:
    "Related Notes 목록 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RECOMMENDATION_EXECUTION_STATE]:
    "추천 실행 상태 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RELATED_NOTE_CANDIDATES]:
    "Related Note 후보 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RECOMMENDATION_SOURCE]:
    "추천 대상 Note 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RECOMMENDATION_EXCLUSIONS]:
    "추천 제외 대상 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_QUERY_EXPANSION_RESPONSE]:
    "검색 질의 확장 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_QUERY_EXPANSION_RESPONSE]:
    "검색 질의 확장 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_RECOMMENDATION_RESPONSE]:
    "추천 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_RECOMMENDATION_RESPONSE]:
    "추천 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_RECOMMENDATIONS]:
    "추천 노트 확인",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_VERIFICATION_RESPONSE]:
    "추천 검증 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_VERIFICATION_RESPONSE]:
    "추천 검증 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_VERIFICATIONS]:
    "추천 검증 결과 확인",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.REPLACE_RECOMMENDATIONS]:
    "AI 추천 교체",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.CLAIM_RECOMMENDATION_EXECUTION]:
    "추천 실행 선점",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_RECOMMENDATION_EXECUTION_CLAIM]:
    "추천 실행 선점 완료",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.GET_DAILY_USAGE]:
    "일일 사용량 조회",

  // 과거 operational_errors 행의 표시 호환만 유지한다.
  create_recommendation_run: "추천 실행 이력 생성",
  update_recommendation_run: "추천 실행 이력 갱신",
  complete_recommendation_run: "추천 실행 이력 완료",
} as const;

/**
 * Related Notes 작업 내부의 운영 오류 단계입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_STAGES = {
  EXECUTION: "execution",
} as const;

/**
 * Related Notes 운영 오류 단계의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_STAGE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_STAGES.EXECUTION]: "실행",
} as const;

/**
 * Related Notes 운영 오류를 식별하는 코드입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_CODES = {
  SOURCE_NOTE_LOAD_FAILED: "RELATED_NOTES_SOURCE_NOTE_LOAD_FAILED",
  RELATED_NOTES_LOAD_FAILED: "RELATED_NOTES_LOAD_FAILED",
  RECOMMENDATION_EXECUTION_STATE_LOAD_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXECUTION_STATE_LOAD_FAILED",
  RELATED_NOTE_CANDIDATES_LOAD_FAILED:
    "RELATED_NOTES_RELATED_NOTE_CANDIDATES_LOAD_FAILED",

  RECOMMENDATION_SOURCE_LOAD_FAILED:
    "RELATED_NOTES_RECOMMENDATION_SOURCE_LOAD_FAILED",

  RECOMMENDATION_EXCLUSIONS_LOAD_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXCLUSIONS_LOAD_FAILED",

  QUERY_EXPANSION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_QUERY_EXPANSION_RESPONSE_PARSE_FAILED",

  QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED",

  RECOMMENDATION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RESPONSE_PARSE_FAILED",

  RECOMMENDATION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RESPONSE_VALIDATION_FAILED",

  RECOMMENDATIONS_RESOLVE_FAILED:
    "RELATED_NOTES_RECOMMENDATIONS_RESOLVE_FAILED",

  VERIFICATION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_VERIFICATION_RESPONSE_PARSE_FAILED",

  VERIFICATION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_VERIFICATION_RESPONSE_VALIDATION_FAILED",

  VERIFICATIONS_RESOLVE_FAILED: "RELATED_NOTES_VERIFICATIONS_RESOLVE_FAILED",

  RECOMMENDATIONS_REPLACE_FAILED:
    "RELATED_NOTES_RECOMMENDATIONS_REPLACE_FAILED",

  RECOMMENDATION_EXECUTION_CLAIM_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXECUTION_CLAIM_FAILED",

  RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED",

  /*
   * Related Notes 일일 AI 추천 사용량을 조회하는 과정에서
   * DB/RPC 호출 자체가 실패한 경우 기록하는 오류입니다.
   *
   * 사용량 조회 실패는 Related Notes 자체의 조회를 중단시키지 않고,
   * 화면에서는 사용량만 표시하지 않는 best-effort 오류로 처리합니다.
   */
  DAILY_USAGE_LOAD_FAILED: "RELATED_NOTES_DAILY_USAGE_LOAD_FAILED",
} as const;

/**
 * Related Notes 운영 오류 코드의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_CODE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.SOURCE_NOTE_LOAD_FAILED]:
    "기준 Note 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RELATED_NOTES_LOAD_FAILED]:
    "Related Notes 목록 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXECUTION_STATE_LOAD_FAILED]:
    "추천 실행 상태 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RELATED_NOTE_CANDIDATES_LOAD_FAILED]:
    "Related Note 후보 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_SOURCE_LOAD_FAILED]:
    "추천 대상 Note 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXCLUSIONS_LOAD_FAILED]:
    "추천 제외 대상 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.QUERY_EXPANSION_RESPONSE_PARSE_FAILED]:
    "검색 질의 확장 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED]:
    "검색 질의 확장 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RESPONSE_PARSE_FAILED]:
    "추천 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RESPONSE_VALIDATION_FAILED]:
    "추천 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATIONS_RESOLVE_FAILED]:
    "추천 노트 확인 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATION_RESPONSE_PARSE_FAILED]:
    "추천 검증 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATION_RESPONSE_VALIDATION_FAILED]:
    "추천 검증 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATIONS_RESOLVE_FAILED]:
    "추천 검증 결과 확인 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATIONS_REPLACE_FAILED]:
    "AI 추천 교체 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXECUTION_CLAIM_FAILED]:
    "추천 실행 선점 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED]:
    "추천 실행 선점 완료 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.DAILY_USAGE_LOAD_FAILED]:
    "일일 사용량 조회 실패",

  // 과거 operational_errors 행의 표시 호환만 유지한다.
  RELATED_NOTES_RECOMMENDATION_RUN_CREATE_FAILED: "추천 실행 이력 생성 실패",
  RELATED_NOTES_RECOMMENDATION_RUN_UPDATE_FAILED: "추천 실행 이력 갱신 실패",
  RELATED_NOTES_RECOMMENDATION_RUN_COMPLETE_FAILED: "추천 실행 이력 완료 실패",
} as const;

export type RelatedNotesOperationalErrorOperationType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS];

export type RelatedNotesOperationalErrorStageType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_STAGES)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_STAGES];

export type RelatedNotesOperationalErrorCodeType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_CODES)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_CODES];
