/**
 * Related Notes 운영 오류 기능입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_FEATURES = {
  RELATED_NOTES: "related-notes",
} as const;

/**
 * Related Notes 운영 오류 기능의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_FEATURE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_FEATURES.RELATED_NOTES]: "Related Notes",
} as const;

/**
 * Related Notes에서 운영 오류를 기록하는 작업입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS = {
  LOAD_RECOMMENDATION_SOURCE: "load_recommendation_source",

  LOAD_RECOMMENDATION_EXCLUSIONS: "load_recommendation_exclusions",

  PARSE_QUERY_EXPANSION_RESPONSE: "parse_query_expansion_response",
  VALIDATE_QUERY_EXPANSION_RESPONSE: "validate_query_expansion_response",

  PARSE_RECOMMENDATION_RESPONSE: "parse_recommendation_response",
  VALIDATE_RECOMMENDATION_RESPONSE: "validate_recommendation_response",
  RESOLVE_RECOMMENDATIONS: "resolve_recommendations",

  PARSE_VERIFICATION_RESPONSE: "parse_verification_response",
  VALIDATE_VERIFICATION_RESPONSE: "validate_verification_response",
  RESOLVE_VERIFICATIONS: "resolve_verifications",

  REPLACE_RECOMMENDATIONS: "replace_recommendations",

  CLAIM_RECOMMENDATION_EXECUTION: "claim_recommendation_execution",
  COMPLETE_RECOMMENDATION_EXECUTION_CLAIM:
    "complete_recommendation_execution_claim",

  CREATE_RECOMMENDATION_RUN: "create_recommendation_run",
  UPDATE_RECOMMENDATION_RUN: "update_recommendation_run",
  COMPLETE_RECOMMENDATION_RUN: "complete_recommendation_run",
} as const;

/**
 * Related Notes 운영 오류 작업의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_OPERATION_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RECOMMENDATION_SOURCE]:
    "추천 대상 Note 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.LOAD_RECOMMENDATION_EXCLUSIONS]:
    "추천 제외 대상 조회",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_QUERY_EXPANSION_RESPONSE]:
    "검색 질의 확장 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_QUERY_EXPANSION_RESPONSE]:
    "검색 질의 확장 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_RECOMMENDATION_RESPONSE]:
    "추천 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_RECOMMENDATION_RESPONSE]:
    "추천 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_RECOMMENDATIONS]:
    "추천 노트 확인",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.PARSE_VERIFICATION_RESPONSE]:
    "추천 검증 응답 파싱",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.VALIDATE_VERIFICATION_RESPONSE]:
    "추천 검증 응답 검증",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.RESOLVE_VERIFICATIONS]:
    "추천 검증 결과 확인",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.REPLACE_RECOMMENDATIONS]:
    "AI 추천 교체",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.CLAIM_RECOMMENDATION_EXECUTION]:
    "추천 실행 선점",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_RECOMMENDATION_EXECUTION_CLAIM]:
    "추천 실행 선점 완료",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.CREATE_RECOMMENDATION_RUN]:
    "추천 실행 이력 생성",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.UPDATE_RECOMMENDATION_RUN]:
    "추천 실행 이력 갱신",

  [RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS.COMPLETE_RECOMMENDATION_RUN]:
    "추천 실행 이력 완료",
} as const;

/**
 * Related Notes 작업 내부의 운영 오류 단계입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_STAGES = {
  EXECUTION: "execution",
} as const;

/**
 * Related Notes 운영 오류 단계의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_STAGE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_STAGES.EXECUTION]: "실행",
} as const;

/**
 * Related Notes 운영 오류를 식별하는 코드입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_CODES = {
  RECOMMENDATION_SOURCE_LOAD_FAILED:
    "RELATED_NOTES_RECOMMENDATION_SOURCE_LOAD_FAILED",

  RECOMMENDATION_EXCLUSIONS_LOAD_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXCLUSIONS_LOAD_FAILED",

  QUERY_EXPANSION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_QUERY_EXPANSION_RESPONSE_PARSE_FAILED",

  QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED",

  RECOMMENDATION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RESPONSE_PARSE_FAILED",

  RECOMMENDATION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RESPONSE_VALIDATION_FAILED",

  RECOMMENDATIONS_RESOLVE_FAILED:
    "RELATED_NOTES_RECOMMENDATIONS_RESOLVE_FAILED",

  VERIFICATION_RESPONSE_PARSE_FAILED:
    "RELATED_NOTES_VERIFICATION_RESPONSE_PARSE_FAILED",

  VERIFICATION_RESPONSE_VALIDATION_FAILED:
    "RELATED_NOTES_VERIFICATION_RESPONSE_VALIDATION_FAILED",

  VERIFICATIONS_RESOLVE_FAILED: "RELATED_NOTES_VERIFICATIONS_RESOLVE_FAILED",

  RECOMMENDATIONS_REPLACE_FAILED:
    "RELATED_NOTES_RECOMMENDATIONS_REPLACE_FAILED",

  RECOMMENDATION_EXECUTION_CLAIM_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXECUTION_CLAIM_FAILED",

  RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED",

  RECOMMENDATION_RUN_CREATE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RUN_CREATE_FAILED",

  RECOMMENDATION_RUN_UPDATE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RUN_UPDATE_FAILED",

  RECOMMENDATION_RUN_COMPLETE_FAILED:
    "RELATED_NOTES_RECOMMENDATION_RUN_COMPLETE_FAILED",
} as const;

/**
 * Related Notes 운영 오류 코드의 표시 이름입니다.
 */
export const RELATED_NOTES_OPERATIONAL_ERROR_CODE_LABELS = {
  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_SOURCE_LOAD_FAILED]:
    "추천 대상 Note 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXCLUSIONS_LOAD_FAILED]:
    "추천 제외 대상 조회 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.QUERY_EXPANSION_RESPONSE_PARSE_FAILED]:
    "검색 질의 확장 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.QUERY_EXPANSION_RESPONSE_VALIDATION_FAILED]:
    "검색 질의 확장 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RESPONSE_PARSE_FAILED]:
    "추천 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RESPONSE_VALIDATION_FAILED]:
    "추천 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATIONS_RESOLVE_FAILED]:
    "추천 노트 확인 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATION_RESPONSE_PARSE_FAILED]:
    "추천 검증 응답 파싱 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATION_RESPONSE_VALIDATION_FAILED]:
    "추천 검증 응답 검증 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.VERIFICATIONS_RESOLVE_FAILED]:
    "추천 검증 결과 확인 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATIONS_REPLACE_FAILED]:
    "AI 추천 교체 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXECUTION_CLAIM_FAILED]:
    "추천 실행 선점 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_EXECUTION_CLAIM_COMPLETE_FAILED]:
    "추천 실행 선점 완료 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RUN_CREATE_FAILED]:
    "추천 실행 이력 생성 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RUN_UPDATE_FAILED]:
    "추천 실행 이력 갱신 실패",

  [RELATED_NOTES_OPERATIONAL_ERROR_CODES.RECOMMENDATION_RUN_COMPLETE_FAILED]:
    "추천 실행 이력 완료 실패",
} as const;

export type RelatedNotesOperationalErrorOperationType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_OPERATIONS];

export type RelatedNotesOperationalErrorStageType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_STAGES)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_STAGES];

export type RelatedNotesOperationalErrorCodeType =
  (typeof RELATED_NOTES_OPERATIONAL_ERROR_CODES)[keyof typeof RELATED_NOTES_OPERATIONAL_ERROR_CODES];
